/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

unsigned char variable1 = 0;

uint8_t variable2 = 0;

uint32_t variable3 = 0;

int8_t variable4 = 0;

uint8_t x,y,z;

int16_t m = 2, n = 3, t =-5;

char MiPrimerString[5] = "Linux";

char MiprimerCaracter = 'A';

uint8_t variable5 = 0; int32_t variable6 = 0;

int main(void)
{

	//Esta es una prueba
	char sizechar = sizeof(variable6);

	char sizeMiPrimerString = sizeof(MiPrimerString);

	(void) sizechar;

	(void) sizeMiPrimerString;

	m = m + n;
	m += n;

	m = m + 1;
	m += 1;
	m ++;

	m *= n;
	m /= n;
	m %= n;

	m <<= n;
	m >>= n;




    /* Loop forever */
	while(1){

	}
}

